<?php

function remind_subcommittees_mail($key, &$message, $subcommittee) {
    $CC_to = "council@linux.org.au";
    $message['headers']['CC'] = $CC_to;

    switch($key) {
        case 'remind':
            $message['subject'] = t('Subcommittee report for !subcommittee is due.', array('!subcommittee' => $subcommittee->title));
$message['body'][] = t("Hi there,

Your !period report for the !subcommittee subcommittee is due on the !duedate.

Please go to !reporturl and enter your report. You may enter it directly into the form, attach a copy or link to one hosted elsewhere. 

Your report only needs to provide a quick update of how things are progressing for your subcommittee.
This can be as short as some simple dot points to let the council know that things are going smoothly.
Please follow the instructions on the submission URL.

Linux Australia really appreciates your ongoing efforts and commitment and help in your roles.

Thanks,
The Linux Australia Council
", array('!period' => $subcommittee->field_reporting_period[0]['value'], '!subcommittee' => $subcommittee->title ,'!reporturl' => url('node/add/report', array('absolute' => true)), '!duedate' => date('Y-m-d', strtotime($subcommittee->field_next_report_date[0]['value']))));
        break;
        case 'overdue':
            $message['subject'] = t('Subcommittee report for !subcommittee is overdue.', array('!subcommittee' => $subcommittee->title));
$message['body'][] = t("Hi there,

Your !period report for the !subcommittee subcommittee is now overdue. The report was due on the !duedate.

Please go to !reporturl and enter your report. You may enter it directly into the form, attach a copy or link to one hosted elsewhere.

Your report only needs to provide a quick update of how things are progressing for your subcommittee.
This can be as short as some simple dot points to let the council know that things are going smoothly.
Please follow the instructions on the submission URL.

Linux Australia really appreciates your ongoing efforts and commitment and help in your roles. If you are unable to submit your report for any reasons, please contact council@linux.org.au.

Thanks,
The Linux Australia Council
", array('!period' => $subcommittee->field_reporting_period[0]['value'], '!subcommittee' => $subcommittee->title, '!reporturl' => url('node/add/report', array('absolute' => true)), '!duedate' => date('Y-m-d', strtotime($subcommittee->field_next_report_date[0]['value']))));
        break;
    }
}

function remind_subcommittees_menu() {
    $items = array();
   
    //Link to the test_module admin page:
    $items['remind_subcommittees'] = array(
        'title' => 'Remind Subcommittees',
        'page callback' => 'remind_subcommittees_check',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE
    );
   
    return $items;
}

function remind_subcommittees_check() {
    $time_values = array(
        'Weekly' => 60*60*24*7,
        'Fortnightly' => 60*60*24*14,
        'Monthly' => 60*60*24*30,
        'Bimonthly' => 60*60*24*60,
        'Quarterly' => 60*60*24*91,
        'Half Yearly' => 60*60*24*182,
        'Annually' => 60*60*24*365,
    );

    $query = db_query("SELECT * FROM {node} WHERE type = 'subcommittee'");
    while ( $row = db_fetch_object($query) ) {
        $subcommittee = node_load($row->nid);
        $query2 = db_query("SELECT * FROM {content_type_report}, {node} WHERE content_type_report.field_report_references_nid = %d AND content_type_report.nid = node.nid ORDER BY node.created DESC LIMIT 1", $row->nid);
        $last_report = db_fetch_object($query2);
        $report_period = $time_values[$subcommittee->field_reporting_period[0]['value']];
        $last_reminder = strtotime($subcommittee->field_subcommittee_last_reminder[0]['value']);
        $due_time = strtotime($subcommittee->field_next_report_date[0]['value']);
        if ( $subcommittee->field_subcommittee_status[0]['value'] == 'Active subcommittee' ) {
            if ( $last_report->created >= $due_time ) {
                // report already submitted... Automatically update the due date of the next one
                $subcommittee->field_next_report_date[0]['value'] = date('Y-m-d', $due_time + $report_period) . 'T00:00:00';
                node_save($subcommittee);
            }
            else {
                if ( ($due_time - time()) <= (60*60*24*7) ) {
                    // within 7 days of due
                    if ( ($due_time - $last_reminder) >= (60*60*24*7) ) {
                        // haven't already been reminded, so send one
                        remind_subcommittees_send_email($subcommittee);
                    }
                }
                
                if ( time() >= $due_time ) {
                    if ( (time() - $last_reminder) > (60*60*24*3) ) {
                        remind_subcommittees_overdue($subcommittee); // send a reminder every 3 days
                    }
                }
            }
        }
    }
}

function remind_subcommittees_overdue($subcommittee) {
    remind_subcommittees_send_email($subcommittee, 'overdue');
}

function remind_subcommittees_send_email($subcommittee, $key = 'remind') {
    $subcommittee->field_subcommittee_last_reminder[0]['value'] = date('Y-m-d', time()) . 'T00:00:00';
    node_save($subcommittee);
    $alert_to = $subcommittee->field_subcommittee_contact[0]['value'];
    drupal_mail('remind_subcommittees', $key, $alert_to, user_preferred_language($account), $subcommittee);
}

?>
